/hikcam:
  camera:
    ros__parameters:
      url: "package://unicam/calibration/${NAME}.yaml"
      pixel_width: -1
      pixel_height: -1
      timeout: 1.
      device: "usb:0"
      exposure_time: 5000.
      gamma: 15.
